[package]
name = "brainfuck-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vanilla"
path = "src/main_vanilla.rs"

[[bin]]
name = "ir"
path = "src/main_ir.rs"

[[bin]]
name = "jit"
path = "src/main_jit.rs"

[dependencies]
dynasm = "1.2.3"
dynasmrt = "1.2.3"